import * as dotenv from 'dotenv'
dotenv.config()
import { Authentication } from '../../../../src/application/auth/jwt/authentication'

describe('should be able to pass the authentication with correct code', () => {
  const AuthenticationService = new Authentication()

  it('should be able to verify code generated by the service', async () => {
    const plainText = 'testing'
    const code = await AuthenticationService.sign({ plainText })
    const isVerified = await AuthenticationService.verify(code)
    expect(isVerified).toBeTruthy()
  })

  it('should be able to reject the wrong code generated from the bad guys', async () => {
    const plainText = 'testing'
    await AuthenticationService.sign({ plainText })
    const incorrectCode = 'karmaisabitch'
    try {
      await AuthenticationService.verify(incorrectCode)
    } catch (error) {
      expect(error.message).toBe('NOT_AUTHENTICATED')
    }
  })

  it('should be able to reject the empty code', async () => {
    const plainText = 'testing'
    await AuthenticationService.sign({ plainText })
    const emptyCode = ''
    try {
      await AuthenticationService.verify(emptyCode)
    } catch (error) {
      expect(error.message).toBe('NOT_AUTHENTICATED')
    }
  })
})
